### ISSUE TITLE
Release v0.7?

### ISSUE THREAD

**Issue by dkarrasch** [JuliaGeometry/Quaternions.jl#112]
Please, please consider releasing v0.7 very soon. The currently released state of the package can be viewed as nearly-broken. This is due to the many deprecation warnings. For instance, see https://github.com/JuliaLinearAlgebra/GenericLinearAlgebra.jl/pull/91, whose CI was failing, because it couldn't finish its test suite within 5 hours. Usually, it takes just a handful of minutes. Essentially all of the 5 hours were spent on computing the QR decomposition of a 50x50 quaternion matrix. There, dot products of quaternion vectors are computed, and in every product of quaternions the package itself uses a quaternion constructor that is deprecated, so it's not even the "fault" of the downstream package. Releasing a new minor version should do no harm, because all downstream packages are stuck at v0.6.x by their `Project.toml`. Anyone who wants to upgrade will run CI and fix all issues that appear, so there shouldn't be any breakage in the ecosystem.

**Comment by sethaxen** [comment]
Thanks for pinging us, and yes, we should do this soon. @hyrodium is #108 the only thing missing before we can release?

**Comment by hyrodium** [comment]
#108 is the biggest change, but we also have #62 and #86. These two are not hard to fix.

**Comment by sethaxen** [comment]
I agree, all of these should be in the release. I'll finish up #108 today or tomorrow.

**Comment by sethaxen** [comment]
@hyrodium I can also take removing all complex promotion to quaternion unless you've already started on it.

**Comment by hyrodium** [comment]
Thanks for the suggestion! I opened #113 to remove complex promotions. I will update #95 and #111 today or tomorrow.

**Comment by hyrodium** [comment]
The next version `v0.7.0` will be released soon! https://github.com/JuliaRegistries/General/pull/73647
