### ISSUE TITLE
DualQuaternion construction from Duals

### ISSUE THREAD

**Issue by dbeach24** [JuliaGeometry/Quaternions.jl#16]
It looks like the type `DualQuaternion` may be constructed from four `DualNumbers.Dual` values.  However, when I try this, I get an error.

It appears that (in my version of DualNumbers, anyway) the field names are `value` and `epsilon`.  `DualQuaternion` is trying to access a field called `re`.

**Comment by hyrodium** [comment]
Please refer to other comments in #79 and #92.
