### ISSUE TITLE
adding conversion functionality

### ISSUE THREAD

**Issue by huckl3b3rry87** [JuliaGeometry/Quaternions.jl#24]
I am wondering if it would be appropriate to add some conversion functionality to this package, for instance converting from Quaternions to Euler angles and vice versa. For now, maybe we can just import the functionality from C or python modules such as [these](http://wiki.ros.org/action/show/geometry2/RotationMethods?action=show&redirect=geometry%2FRotationMethods#btMatrix3x3)

**Comment by hyrodium** [comment]
[Rotations.jl](https://github.com/JuliaGeometry/Rotations.jl) supports the features such as conversion from quaternion to Euler's angles. (https://github.com/JuliaGeometry/Rotations.jl/pull/175)

Note that this package `Quaternions` mainly focuses on algebraic properties.
