### ISSUE TITLE
Not full support Quaternion{BigFloat}

### ISSUE THREAD

**Issue by denius** [JuliaGeometry/Quaternions.jl#25]
There is omitted comparison operations
```julia
julia> q=Quaternion(BigFloat(0),0,0,0);
julia> zero(q)==zero(q)
false
```
Could you to add explicit specialized functions for `BigFloat`?

**Comment by denius** [comment]
I found out that `Quadmath.jl` appeared, for which this bug is not relevant.

**Comment by hyrodium** [comment]
The bug still exists, so it seems better to reopen this issue. (I don't have permission)

**Comment by hyrodium** [comment]
Ah, this is also solved by https://github.com/JuliaGeometry/Quaternions.jl/pull/52.
