### ISSUE TITLE
What is n::Bool in the Quaternion constructor?

### ISSUE THREAD

**Issue by homocomputeris** [JuliaGeometry/Quaternions.jl#36]
What is `n::Bool=false` in the Quaternion constructor? What does it represent?

**Comment by goretkin** [comment]
The `Quaternion` type is defined here: 
https://github.com/JuliaGeometry/Quaternions.jl/blob/01d45b4f345fb91945211d3c6387da4b5934e7d7/src/Quaternion.jl#L1-L7

It includes a field to indicate whether the quaternion has unit length. The killer app for quaternions is that a unit-length quaternion can represent a rotations in 3D. You might think of it as a way to cache the computation of computing the length.

FYI, not many libraries implement quaternions in this way from what I see.

**Comment by homocomputeris** [comment]
The problem with this implementation is (or was, at least) that one could create a non-unit quaternion and set `norm=True`, basically making the argument useless.

**Comment by goretkin** [comment]
The point is to avoid unnecessary computation, so I don't see a way around that problem.

**Comment by homocomputeris** [comment]
The constructor should check it a passed quadruple can represent a unit quaternion.

**Comment by goretkin** [comment]
That "check" is exactly the unnecessary computation I mean. There are cases where you know that the quadruple has unit length. For example, if you wanted to ignore floating point issues, you might want to assert that multiplying two unit-length quaternions produces a unit-length quaternion.

**Comment by hyrodium** [comment]
The `.norm` field will be removed in #75, and it will not be documented.
