### ISSUE TITLE
Lipschitz and Hurwitz quaternions

### ISSUE THREAD

**Issue by chrisvwx** [JuliaGeometry/Quaternions.jl#45]
My understanding is that the current implementation of Quaternions with Int inputs is aligned with the idea of a Lipschitz quaternion. 
```julia
julia> Quaternion(1,2,3,4)
Quaternion{Int64}(1, 2, 3, 4, false)
```
On the other hand, in many cases one wants a [Hurwitz quaternion](https://en.wikipedia.org/wiki/Hurwitz_quaternion). Even though I don't have a clear idea how a Hurwitz quaternion would be integrated with this package, I thought perhaps an issue about it would at least provide a place to discuss the topic.

**Comment by chakravala** [comment]
i think the obvious solution is to implement another "<:Real" type which stores an integer, but divides it by 2 and prints it, and then use that as coefficients

**Comment by chakravala** [comment]
Alright, I went ahead and created the https://github.com/chakravala/HalfIntegers.jl package, let me know if you try it.

**Comment by chakravala** [comment]
Apparently there is another existing repository doing the same thing https://github.com/sostock/HalfIntegers.jl

**Comment by hyrodium** [comment]
I think this issue is solved with `HalfIntegers.jl`. It would be nice to have more documentation for Hurwitz quaternions.
