### ISSUE TITLE
`slerp` breaks flag for quaternion normalization

### ISSUE THREAD

**Issue by hyrodium** [JuliaGeometry/Quaternions.jl#51]
```julia
julia> q1 = Quaternion(1.0, 0.0, 0.0, 0.0, true)
Quaternion{Float64}(1.0, 0.0, 0.0, 0.0, true)

julia> q2 = Quaternion(0.0, 1.0, 0.0, 0.0, true)
Quaternion{Float64}(0.0, 1.0, 0.0, 0.0, true)

julia> slerp(q1,q2,0.3)
Quaternion{Float64}(0.8910065241883678, 0.45399049973954675, 0.0, 0.0, false)
```
The flag `false` should be `true` here because `slerp` keeps norm of quaternion if the input quaternions are unit quaternions.

**Comment by sethaxen** [comment]
Since #60 proposes a breaking change and this issue doesn't, proceeding with a PR anyways would be useful.

**Comment by hyrodium** [comment]
Oh, I just noticed we also have `linpol` funciton.
```julia
julia> q1 = Quaternion(1.,0.,0.,0.,true)
QuaternionF64(1.0, 0.0, 0.0, 0.0, true)

julia> q2 = Quaternion(0.,1.,0.,0.,true)
QuaternionF64(0.0, 1.0, 0.0, 0.0, true)

julia> linpol(q1, q2, 0.2)
QuaternionF64(0.9510565162951535, 0.3090169943749474, 0.0, 0.0, true)

julia> slerp(q1, q2, 0.2)
QuaternionF64(0.9510565162951535, 0.3090169943749474, 0.0, 0.0, false)
```

**Comment by sethaxen** [comment]
Are they entirely equivalent, or is there some combination of inputs for which they will produce different results?

**Comment by hyrodium** [comment]
Note that these functions return different values for non-unit quaternion.
```julia
julia> q3 = Quaternion(2.,1.,0.,0.,true)
QuaternionF64(2.0, 1.0, 0.0, 0.0, true)

julia> q4 = Quaternion(3.,0.,0.,0.,true)
QuaternionF64(3.0, 0.0, 0.0, 0.0, true)

julia> slerp(q3, q4, 0.2)
QuaternionF64(2.0, 1.0, 0.0, 0.0, true)

julia> linpol(q3, q4, 0.2)
QuaternionF64(2.2, 0.8, 0.0, 0.0, true)
```
* `slerp` returns the first quaternion if the cosine is larger than 1. This seems buggy for me.
  * https://github.com/JuliaGeometry/Quaternions.jl/blob/v0.4.8/src/Quaternion.jl#L285
* `linpol` normalizes arguments, and the return value is always unit quaternion.
  * https://github.com/JuliaGeometry/Quaternions.jl/blob/v0.4.8/src/Quaternion.jl#L156-L158

My question is, what's the expected behavior of `slerp` with non-unit quaternion?
I think we have the following choices:

* Normalize all input quaternions, and the return value is always unit quaternion. (like `linpol`)
* Throws `DomainError` for non-unit quaternion.
* Return `exp(log(q1)*(1-t) + log(q2)*t)` for any quaternions.

**Comment by hyrodium** [comment]
The following are references on slerp, all of which deal with unit quaternions.

>Slerp is shorthand for spherical linear interpolation

https://en.wikipedia.org/wiki/Slerp

> spherical interpolating between the rotated value ...

http://www.euclideanspace.com/maths/algebra/realNormedAlgebra/quaternions/slerp/

>Spherically interpolates between quaternions a and b by ratio t.

https://docs.unity3d.com/ScriptReference/Quaternion.Slerp.html

**Comment by sethaxen** [comment]
For additional background, `linpol` was present in the original check-in of the package (351d6575d), and `slerp` was added in #6, with no discussion about `linpol`.

**Comment by hyrodium** [comment]
@keesvp @SimonDanisch 
Do you have any thoughts on this?

**Comment by hyrodium** [comment]
I tried searching for `linpol` in GitHub public repositories, but I couldn't find it.
https://github.com/search?q=language%3Ajulia+linpol&type=code

**Comment by hyrodium** [comment]
On the current master branch, `slerp` is faster than `linpol`.

```julia
julia> q1 = Quaternion(1.,0,0,0,true)
QuaternionF64(1.0, 0.0, 0.0, 0.0, true)

julia> q2 = Quaternion(0,1.,0,0,true)
QuaternionF64(0.0, 1.0, 0.0, 0.0, true)

julia> slerp(q1,q2,0.2)
QuaternionF64(0.9510565162951535, 0.3090169943749474, 0.0, 0.0, false)

julia> linpol(q1,q2,0.2)
QuaternionF64(0.9510565162951535, 0.3090169943749474, 0.0, 0.0, true)

julia> @benchmark slerp($q1,$q2,0.2)
BenchmarkTools.Trial: 10000 samples with 994 evaluations.
 Range (min … max):  30.258 ns … 47.363 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     30.450 ns              ┊ GC (median):    0.00%
 Time  (mean ± σ):   30.738 ns ±  1.569 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

   █                                                           
  ▇█▄▂▂▂▁▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▂▂▁▂▂▂▂▂▂▂ ▂
  30.3 ns         Histogram: frequency by time        37.4 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.

julia> @benchmark linpol($q1,$q2,0.2)
BenchmarkTools.Trial: 10000 samples with 991 evaluations.
 Range (min … max):  40.956 ns … 120.753 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     41.835 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):   42.864 ns ±   5.312 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

  ▄█▇▂                                                      ▁▂ ▁
  ████▆▆▇██▇▅▇▆▅▁▃▄▅▁▃▃▄▃▁▁▅▄▄▅▃▁▄▄▃▄▃▄▄▃▃▄▁▁▁▃▄▁▁▁▁▁▁▃▁▁▃▁███ █
  41 ns         Histogram: log(frequency) by time      67.6 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.
```
