### ISSUE TITLE
type of element unparametrized and one() not implemented

### ISSUE THREAD

**Issue by kellertuer** [JuliaGeometry/Quaternions.jl#54]
I was just stumbling across something interesting. In our code we have a function that determines the element type of a vector like 

```
number_eltype(::AbstractArray{T}) where {T<:Number} = T
```

and we use this to allocate new variables like

```
one(number_eltype(pi))
```

Now if I take a vector of Quaternions (and floats internally)

```
p = Quaternion[1.0 + 0im, 0.0, 0.0]
```

now

```
julia> number_eltype(p)
Quaternion
```

just returns `Quaternion` not `Quaternion{Float64}`

so we get

```
one(number_eltype(p))
Quaternion{Int64}(1, 0, 0, 0, true)
```

Is there a possibility to get the `T` in the first function to be parametrised?
The main problem seems to be that `p` is a `Vector{Quaternion}` and not a `Vector{Quaternion{Float64}}' ?

I also noticed that maybe `one(p)` would be something nice to have for vector os Quaternions.

Here's the MWE to test

```
using Quaternions
number_eltype(::AbstractArray{T}) where {T<:Number} = T
p = Quaternion[1.0 + 0im, 0.0, 0.0]
number_eltype(p)
one(number_eltype(p))
typeof(p)
```

**Comment by kellertuer** [comment]
For the first – yes I noticed that this is usual and we found a way around – but it seems a little unexpected as first.

For `one(p)`– well the quaternions form a vector space, so `one(p)` should return a unit vector? I did not get that to work.

**Comment by kellertuer** [comment]
My main point here is maybe that the documentation could be improved, I might contribute to this when I find time.

**Comment by hyrodium** [comment]
>For one(p)– well the quaternions form a vector space, so one(p) should return a unit vector? I did not get that to work.

`one(p::Vector{<Quaternion})` should throw `MethodError` like `one([1,2,2])`.

```julia
julia> one([1,2,2])
ERROR: MethodError: no method matching one(::Vector{Int64})
Closest candidates are:
  one(::Union{Type{T}, T}) where T<:AbstractString at ~/julia/julia-1.7.2/share/julia/base/strings/basic.jl:262
  one(::Union{Type{P}, P}) where P<:Dates.Period at ~/julia/julia-1.7.2/share/julia/stdlib/v1.7/Dates/src/periods.jl:54
  one(::AbstractIrrational) at ~/julia/julia-1.7.2/share/julia/base/irrationals.jl:153
  ...
Stacktrace:
 [1] top-level scope
   @ REPL[1]:1

julia> 
```

If you need a unit vector, `LinearAlgebra.normalize` can be used.

**Comment by sethaxen** [comment]
> For `one(p)`– well the quaternions form a vector space, so `one(p)` should return a unit vector? I did not get that to work.

`one` in Julia returns a multiplicative identity, so unless one endowed a vector type `MyVector` with some specific algebraic structure so that `*(::MyVector, ::MyVector)` is implemented (which would likely be useless because it would break a lot of assumptions of `*` in Base), then `one(::MyVector)` should always error.

**Comment by kellertuer** [comment]
Sure, thanks for the explanation. Then, we can basically close this, since the only thing left is only midlly related to the issue – which is the wish for more documentation :)
