### ISSUE TITLE
`Quaternions.imag` is slow with `Vector`

### ISSUE THREAD

**Issue by hyrodium** [JuliaGeometry/Quaternions.jl#61]
It seems better to have the return value with type `Tuple` instead of `Vector`.
```julia
julia> using Quaternions, BenchmarkTools

julia> q = Quaternion(1,2,3,4)
Quaternion{Int64}(1, 2, 3, 4, false)

julia> function new_imag(q::Quaternion)
           (q.v1,q.v2,q.v3)
       end
new_imag (generic function with 1 method)

julia> Quaternions.imag(q)
3-element Vector{Int64}:
 2
 3
 4

julia> new_imag(q)
(2, 3, 4)

julia> @benchmark Quaternions.imag($q)

BenchmarkTools.Trial: 10000 samples with 997 evaluations.
 Range (min … max):  20.596 ns …  1.775 μs  ┊ GC (min … max): 0.00% … 98.12%
 Time  (median):     22.907 ns              ┊ GC (median):    0.00%
 Time  (mean ± σ):   26.725 ns ± 65.403 ns  ┊ GC (mean ± σ):  9.71% ±  3.92%

    ▂▆██▇▅▃▂▂▁                             ▁▁▁▁               ▂
  ▄▆██████████▇███▇▇▇▆▆▅▅▇▆▄▆▇▇▆▆▆▅▅▄▅▅▅▅▆██████▇▇▆▅▅▅▅▄▅▄▆▇▇ █
  20.6 ns      Histogram: log(frequency) by time      44.4 ns <

 Memory estimate: 80 bytes, allocs estimate: 1.

julia> @benchmark new_imag($q)
BenchmarkTools.Trial: 10000 samples with 1000 evaluations.
 Range (min … max):  0.977 ns … 10.895 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     2.375 ns              ┊ GC (median):    0.00%
 Time  (mean ± σ):   2.397 ns ±  0.232 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

                                            █                 
  ▂▁▁▁▁▁▁▁▁▁▂▁▂▁▁▂▁▁▁▁▁▁▁▁▁▂▁▂▁▁▃▁▁▁▁▁▁▁▂▁▅▁█▁▁▇▁▁▁▁▁▁▁▂▁▃▁▃ ▂
  0.977 ns       Histogram: frequency by time        2.86 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.
```
Note that this makes a breaking change.

**Comment by sethaxen** [comment]
The downside here is that `Tuple`s don't have mathematical operations defined. So e.g. `2 * imag(q)` or `imag(q) + imag(p)` would raise an error. It would be better to use something like StaticArrays here, whose underlying storage is a tuple, but we would need to check that this doesn't affect the load time of the package (StaticArrays depends only on the stdlib).

**Comment by hyrodium** [comment]
Hmm, I understand the downside but I couldn't find a use-case of the mathematical operations, in both my use-case and this repository.
If someone needs the operations, he/she can just call `SVector(imag(q))`. It seems better to have less dependencies even if the package is light.

**Comment by sethaxen** [comment]
Yes, this package doesn't use `imag` much because the resulting `Vector` would be far less efficient to work with than just accessing the corresponding fields.

In your use case, how do you use `imag`? In my opinion, the `imag` function is unfortunate, since it isn't `Base.imag`, and it confuses users. And it returns something that is inherently inefficient.

> If someone needs the operations, he/she/xe can just call `SVector(imag(q))`. It seems better to have less dependencies even if the package is light.

A counterpoint is if a user wants a tuple of the imaginary parts, they can just do `(q.v1,q.v2,q.v3)`. It's more annoying for octonions though.

**Comment by hyrodium** [comment]
>In your use case, how do you use `imag`?

>A counterpoint is if a user wants a tuple of the imaginary parts, they can just do `(q.v1,q.v2,q.v3)`. It's more annoying for octonions though.

I'd like to use the `imag` method as a getter method. I can't remember the name of fields of the struct, so it's better to have the getter method. For the same reason, I mainly use `real(c::Complex)` and `imag(c::Complex)` instead of `c.re` or `c.im`.  (`re, im` / `real, imag`, `s, v1, v2, v3` / `v0, v1, v2, v3` / `w, x, y, z`.... :thinking: )

>In my opinion, the imag function is unfortunate, since it isn't Base.imag, and it confuses users. And it returns something that is inherently inefficient.

I agree with that. Should we add a new function `imagparts` function as a getter method, and deprecat the `imag` function?

**Comment by sethaxen** [comment]
> I agree with that. Should we add a new function `imagparts` function as a getter method, and deprecate the `imag` function?

Yes, I think this is a good idea. Although maybe `imag_parts` is better.
We can use something like `Base.@deprecate imag(x) collect(imag_parts(x))` then and switch internal uses of `imag` to use `imag_parts` instead.

**Comment by sethaxen** [comment]
While I don't think it should be part of the same PR, I think `imag_parts` could also be used to do some code simplification. e.g.
```julia
abs_imag(q::Quaternion) = hypot(imag_part(q)...)
abs(q::Quaternion) = hypot(real(q), imag_part(q)...)
abs2(q::Quaternion) = abs2(real(q)) + sum(abs2, imag_part(q))
```
Since the size of `Tuple` is known at compile time, the loops get unrolled to generate the same code (I've ignored `norm` here). The benefit is even greater for `Octonion`.

**Comment by hyrodium** [comment]
Thanks for the suggestion!

>`abs_imag(q::Quaternion) = hypot(imag_part(q)...)`

Is it should be with `imag_part`? I'm not a native English speaker, so not sure if plural or singular is better..

**Comment by hyrodium** [comment]
Seems like better with `imag_part` according to wikipedia.
![image](https://user-images.githubusercontent.com/7488140/154963240-0149ee45-f23f-43b8-a184-6db03f9f20a1.png)
https://en.wikipedia.org/wiki/Quaternion

**Comment by sethaxen** [comment]
> Is it should be with `imag_part`?, or just a typo?

Oops, yes, typo. Singular is better.
