### ISSUE TITLE
New Minor Version

### ISSUE THREAD

**Issue by nhz2** [JuliaGeometry/Quaternions.jl#64]
Thank you for fixing the type piracy issue in PR #53.
However, I was relying on that bug somehow in my package because I was using Rotations.jl, and the `normalize` function.
This was very confusing for me to figure out because I don't have a direct dependency on Quaternions.jl, just Rotations.jl, and the function that broke wasn't using any rotations or quaternions.

I think it could be helpful to update the minor version for such a big bug fix, so Rotations.jl will also hopefully release a new version with the fix.

**Comment by sethaxen** [comment]
Nice sleuthing! According to collaborative practices, adopted by many packages in the Julia ecosystem, bug fixes, even if they break user's code, should not be considered breaking changes for versioning: https://github.com/SciML/ColPrac#changes-that-are-not-considered-breaking

This case is unfortunate, but it can happen with any bug that a downstream package comes to depend on the bug and breaks when it is fixed. The best thing to do is make the fix in the packages that depended on the bug.

**Comment by nhz2** [comment]
Okay, that makes sense, I was able to easily fix the issue in my package once I figured out what was wrong.
