### ISSUE TITLE
Adding logo to the document

### ISSUE THREAD

**Issue by hyrodium** [JuliaGeometry/Quaternions.jl#70]
I'm planning to add a logo based on [Cayley Q8 quaternion multiplication graph](https://en.wikipedia.org/wiki/File:Cayley_Q8_quaternion_multiplication_graph.svg).

![image](https://user-images.githubusercontent.com/7488140/155314993-0e948c37-489d-4644-a5b1-98759e3e5b8f.png)

* The left one ignores the -1 vertex. (We can also think of the vertex of -1 as the infinity point)
* The middle one draws -1 vertex as a circle
* The right one is a "complete" graph

I prefer the first one because simplicity is important in logo design.

@sethaxen Do you have any thoughts on this?

**Comment by hyrodium** [comment]
Here's a screenshot of the document with the left logo.

![image](https://user-images.githubusercontent.com/7488140/155321000-06e560d3-92f9-4f09-a02b-850728258083.png)

**Comment by sethaxen** [comment]
Looks very nice! By any chance, are you programmatically generating it? (if so, would be good to have the code for that in the PR as well).

I agree, simpler is better for logos, so I do prefer the left one. Although I'm wondering even what it would look like if you completely removed the cycles including -1 (shown as straight lines in the background). For each of the options, I'd like to see what they look like on dark backgrounds as well and also as a favicon.
Some general thoughts:
- You're using purple to denote the bases (nodes) and red, green, and blue to denote the cycles, but in the Julia logo, red, green, and purple form the circles together, and blue is the outlier. Can you make the bases blue?
- I wonder what it would look like if it was rotated so that the 3 cycles in the middle were laid out similarly to the 3 circles in the Julia logo.

**Comment by hyrodium** [comment]
>Looks very nice! By any chance, are you programmatically generating it? (if so, would be good to have the code for that in the PR as well).

I was using inkscape, but I'm planning to remake it with Luxor.jl:+1:

>Although I'm wondering even what it would look like if you completely removed the cycles including -1 (shown as straight lines in the background). For each of the options, I'd like to see what they look like on dark backgrounds as well and also as a favicon.

Okay, I'll try them later!

>You're using purple to denote the bases (nodes) and red, green, and blue to denote the cycles, but in the Julia logo, red, green, and purple form the circles together, and blue is the outlier. Can you make the bases blue?

I agree that the blue color is an outlier, but I'm also thinking that the purple is the most special color in the Julia logo.

![image](https://user-images.githubusercontent.com/7488140/155533522-3f2e9a36-89ec-48a9-92e2-c42908d3796b.png) ![image](https://user-images.githubusercontent.com/7488140/155533569-e512dcf4-dd70-41d8-ae09-548bd611b56d.png)

I used the RGB color for i,j,k multiplications which are associated with x,y,z-axes rotation, and the xyz axes are usually colored with RGB.

![image](https://user-images.githubusercontent.com/7488140/155534523-7b7231a1-2241-4f11-be78-40f9c0694209.png)

**Comment by hyrodium** [comment]
favicon
![image](https://user-images.githubusercontent.com/7488140/155872078-1336a25d-8155-4299-be16-6dba0b814444.png)

**Comment by hyrodium** [comment]
I've uploaded the script to my gist.
https://gist.github.com/hyrodium/ec1cc636c4e63722d2df8044d462eba7

I personally think that the original one is better, because I feel that the logo is too simple to express the intent without straight lines

**Comment by sethaxen** [comment]
These are looking really nice, and I like the last one quite a bit. I agree it would be better to be less overly-simplified, but also, this is a logo, not a didactic figure.

Can you try 2 more variants for me?
- The last logo, but with the straight lines added back in but at higher transparency. This may make it seem less cluttered.
- Same as above, but also removing arrows.

**Comment by hyrodium** [comment]
Thanks for the suggestions! After thinking about the logo for a while, I now agree that the first logo is a little cluttered.

>The last logo, but with the straight lines added back in but at higher transparency. This may make it seem less cluttered.

![image](https://user-images.githubusercontent.com/7488140/157666871-d9353b4d-04cb-499f-83eb-b5399a6b57a3.png) ![image](https://user-images.githubusercontent.com/7488140/157666937-b3db75af-47e9-4279-82cb-b2daa472afb9.png)

>Same as above, but also removing arrows.

![image](https://user-images.githubusercontent.com/7488140/157667279-b5ea47b5-ba37-456a-9931-a360bf9dd35f.png) ![image](https://user-images.githubusercontent.com/7488140/157667212-b1b9b502-9892-4510-922c-a783d1c8a697.png)

And also, I made another version with different base colors.

![image](https://user-images.githubusercontent.com/7488140/157668106-b1e89ec4-4dd5-4cab-ab5f-7e88d33d8839.png) ![image](https://user-images.githubusercontent.com/7488140/157668176-94bf631b-7e5d-48be-85f5-c49089f34778.png)

![image](https://user-images.githubusercontent.com/7488140/157669087-cc070a29-5f61-416d-8abc-096a9053cf44.png)

I prefer the last one because:

* Less cluttered.
* Can be regarded as a subgraph of [Cayley Q8 quaternion multiplication graph](https://en.wikipedia.org/wiki/File:Cayley_Q8_quaternion_multiplication_graph.svg) with meaningful base colors.

@sethaxen Do you have any thoughts on these?

**Comment by sethaxen** [comment]
Thanks for putting these all together! I agree, I think the last one is best. Though, could you try one variant that moves the arrows to be centered in the long arc instead of offset like they are now>

**Comment by hyrodium** [comment]
This looks better, thanks!

![logo](https://user-images.githubusercontent.com/7488140/157683908-3d0d9790-385b-4b03-81d1-176d3b3d7c32.png)
