### ISSUE TITLE
sqrt( DualQuaterion )  error

### ISSUE THREAD

**Issue by Jeffrey-Sarnoff** [JuliaGeometry/Quaternions.jl#9]
v0.5-dev

julia> adualquat = DualQuaternion( Quaternion(1,3,5,7), Quaternion(8,6,4,2) )
1 + 3im + 5jm + 7km + ( 8 + 6im + 4jm + 2km )du

julia> sqrt(adualquat)
ERROR: type Dual has no field re
 in /(::DualQuaternion{Int64}, ::Dual{Float64}) at ./none:1
 in normalizea(::DualQuaternion{Int64}) at ./none:7
 in log(::DualQuaternion{Int64}) at ./none:2
 in sqrt(::DualQuaternion{Int64}) at ./none:2
 in eval(::Module, ::Any) at ./boot.jl:243

**Comment by hyrodium** [comment]
This issue was already solved in the latest release `v0.5.6`.

```julia
julia> a = DualQuaternion( Quaternion(1,3,5,7), Quaternion(8,6,4,2) )
DualQuaternion{Int64}(Quaternion{Int64}(1, 3, 5, 7, false), Quaternion{Int64}(8, 6, 4, 2, false), false)

julia> sqrt(a)
DualQuaternionF64(QuaternionF64(0.3303164318013798, 0.990949295404142, 1.6515821590069033, 2.3122150226096645, false), QuaternionF64(1.3212657272055226, 3.9637971816165702, -5.285062908822095, 3.3031643180138093, false), false)
```
